### PR TITLE
Handle more than one root key

### PR DESCRIPTION
**Pull request by GufNZ**
Our payload has 2 toplevel keys and the old way only ever passed the first.

### CODE REVIEW

**Comment by GufNZ** [comment]
Rats - hometime and the test failed - will have to take a closer look later...

**Comment by GufNZ** [comment]
@funtusov I got this working.  We'd appreciate being able to get this merged as soon as possible, otherwise we'll have to run with my fork...

**Comment by funtusov** [comment]
Hi! Thanks for the contribution, please add a test case that covers this scenario.

**Comment by GufNZ** [comment]
If this works I'm going to squash to tidy this up.

**Comment by GufNZ** [comment]
That should do it.

**Comment by funtusov** [comment]
Thanks! Published 1.1.0

**Pull request merged**
